name: Commit Changes
permissions: write-all
on: [push]


jobs:
  commit_changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Python script
        run: python indexer.py ./
      - name: Commit new files
        run: |
          ls
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Auto-commit new files" || echo "No changes to commit"
          git push
